name: arborist-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pydantic>=2.6
      - requests>=2.31
      - openai>=1.30
      - outlines>=0.1.0
      - python-dotenv>=1.0
      - fastapi>=0.111
      - uvicorn>=0.30
      - plotly>=5.22
      - python-docx>=1.1.0
      - pypandoc>=1.13
      - pytest>=8.2
      - python-dateutil>=2.9
      - langchain>=0.2
      - langchain-community>=0.2
      - langchain-openai>=0.2
      - transformers>=4.41
      - datasets>=2.20
